Repository jupyter-ai-contrib/jupyter-ai-personas, pull requests merged in 2025-07, with the labels that each got.

#11 Update Personas for dependencies and base code changes
  jupyter_ai_personas/emoji_persona/persona.py
  jupyter_ai_personas/finance_persona/persona.py
  pyproject.toml
Labels: bug

#7 DataAnalyticsTeam Persona
  jupyter_ai_personas/data_analytics_persona/README.md
  jupyter_ai_personas/data_analytics_persona/enhancedPythonTools.py
  jupyter_ai_personas/data_analytics_persona/images/analysis_p1.png
  jupyter_ai_personas/data_analytics_persona/images/analysis_p2.png
  jupyter_ai_personas/data_analytics_persona/images/created_session.png
  jupyter_ai_personas/data_analytics_persona/images/open_chat_selected_persona.png
  jupyter_ai_personas/data_analytics_persona/images/show_test_data.png
  jupyter_ai_personas/data_analytics_persona/images/user_prompt.png
  jupyter_ai_personas/data_analytics_persona/persona.py
  jupyter_ai_personas/data_analytics_persona/test_data.ipynb
  pyproject.toml
Labels: new Persona

#16 Refactor PRReviewPersona.heartbeat function
  jupyter_ai_personas/pr_review_persona/persona.py
Labels: enhancement
